version: '2.1'
services:
  node-odm:
    image: opendronemap/nodeodm:gpu
    ports:
      - "3000"
    restart: unless-stopped
    oom_score_adj: 500
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
